"""Native Git proofs, independently generated bytes; no signature claims in fixtures."""
import base64
from dataclasses import replace
import hashlib
import json
import os
from uuid import uuid4
from pathlib import Path
import subprocess
from types import SimpleNamespace

import pytest
from app.schemas_organization_rea_admission import ReaCiAttestationEvidence, ReaCiSourceRelationEvidence
from app.services import organization_rea_source_relation as relation
from app.services import organization_rea_ci_attestation as ci
from app.services.organization_command import InvalidTransition
from tests.test_organization_rea_ci_attestation import attested, raw_result
from tests.test_organization_rea_compilation import correlated
from tests.test_organization_rea_build import package_setup, board, approve


def witness(trigger='pull_request'):
    objects = {}
    def add(kind, raw):
        oid = relation.object_sha(kind, raw)
        objects[oid] = {'type':kind, 'data_base64':base64.b64encode(raw).decode()}
        return oid
    def tree(entries):
        return add('tree', b''.join(mode.encode()+b' '+name.encode()+b'\0'+bytes.fromhex(oid)
            for name, mode, oid in sorted(entries, key=lambda v:v[0]+('/' if v[1]=='40000' else ''))))
    workflow, helper, verifier = b'workflow\n', b'helper\n', b'verifier\n'
    scripts = tree([('rea_build_repeatability.py','100644',add('blob',helper)), ('rea_ci_attestation.py','100644',add('blob',verifier))])
    workflows = tree([('rea-build-repeatability.yml','100644',add('blob',workflow))])
    github = tree([('workflows','40000',workflows)])
    root = tree([('.github','40000',github), ('scripts','40000',scripts)])
    def commit(parents):
        return add('commit', ('tree '+root+'\n'+''.join('parent '+v+'\n' for v in parents)+'author A <a@b> 1 +0000\ncommitter A <a@b> 1 +0000\n\nmessage\n').encode())
    candidate=commit(['b'*40])
    source=commit(['c'*40,candidate]) if trigger=='pull_request' else candidate
    def encode():return json.dumps({'format':'aios-rea-ci-source-witness.v1','objects':objects},sort_keys=True,separators=(',',':')).encode()
    raw=encode()
    pins=relation.ReaCiSourceRelationTrust(Path('/unused'),'witness.json',ci.sha(raw),ci.sha(verifier),'c'*40 if trigger=='pull_request' else None)
    args=dict(candidate_sha=candidate,ci_source_sha=source,ci_workflow_sha=source,trigger=trigger,pins=pins,workflow_sha256=ci.sha(workflow),helper_sha256=ci.sha(helper))
    return raw,args,objects,encode


@pytest.mark.parametrize('trigger',['pull_request','workflow_dispatch'])
def test_native_proof_binds_shared_tree_and_three_reviewed_paths(trigger):
    raw,args,_,_=witness(trigger)
    summary=relation.verify(raw,**args)
    assert summary['candidate_to_ci_source_relation_verified'] is True
    assert summary['committed_recipe_bytes_match_review'] is True
    assert set(summary) == {'witness_sha256','approved_base_sha','candidate_sha','ci_source_sha','shared_tree_sha','reviewed_workflow_sha256','reviewed_build_helper_sha256','reviewed_verifier_sha256','object_count','candidate_to_ci_source_relation_verified','committed_recipe_bytes_match_review'}


@pytest.mark.parametrize('mutation',['base','candidate','workflow-identity','workflow-pin','helper-pin','verifier-pin','witness-pin','trigger','extra-object','missing-object','hash-bytes','duplicate-json','bad-base64','type'])
def test_relation_rejects_drift_and_untrusted_object_shapes(mutation):
    raw,args,objects,encode=witness()
    if mutation=='base':args['pins']=replace(args['pins'],approved_base_sha='d'*40)
    elif mutation=='candidate':args['candidate_sha']='d'*40
    elif mutation=='workflow-identity':args['ci_workflow_sha']='d'*40
    elif mutation in ('workflow-pin','helper-pin'):args[mutation.split('-')[0]+'_sha256']='0'*64
    elif mutation=='verifier-pin':args['pins']=replace(args['pins'],reviewed_verifier_sha256='0'*64)
    elif mutation=='witness-pin':args['pins']=replace(args['pins'],witness_sha256='0'*64)
    elif mutation=='trigger':args['trigger']='workflow_dispatch'
    elif mutation=='extra-object':
        objects[relation.object_sha('blob',b'extra')]={'type':'blob','data_base64':base64.b64encode(b'extra').decode()}
    elif mutation=='missing-object':objects.pop(args['candidate_sha'])
    elif mutation=='hash-bytes':objects[args['candidate_sha']]['data_base64']=base64.b64encode(b'wrong').decode()
    elif mutation=='bad-base64':objects[args['candidate_sha']]['data_base64']='@@'
    elif mutation=='type':objects[args['candidate_sha']]['type']='tag'
    if mutation in ('extra-object','missing-object','hash-bytes','bad-base64','type'):
        raw=encode();args['pins']=replace(args['pins'],witness_sha256=ci.sha(raw))
    if mutation=='duplicate-json':
        raw=raw.replace(b'{"format":',b'{"format":"wrong","format":',1)
        args['pins']=replace(args['pins'],witness_sha256=ci.sha(raw))
    with pytest.raises(InvalidTransition):relation.verify(raw,**args)


@pytest.mark.parametrize('raw',[b'100644 bad/name\0'+b'1'*20,b'120000 link\0'+b'1'*20,b'160000 submodule\0'+b'1'*20,b'100644 x\0'+b'1'*19,b'100644 x\0'+b'1'*20+b'100644 x\0'+b'2'*20,b'100644 z\0'+b'1'*20+b'100644 a\0'+b'2'*20,b'100644 ..\0'+b'1'*20])
def test_native_tree_rejects_unsafe_nonregular_duplicate_and_unsorted_entries(raw):
    with pytest.raises(InvalidTransition):relation.tree(raw)


@pytest.mark.parametrize('raw',[b'tree '+'a'.encode()*40+b'\n\na',b'tree '+'a'.encode()*40+b'\nauthor A <a@b> 1 +0000\ncommitter A <a@b> 1 +0000\nparent '+'b'.encode()*40+b'\n\nm',b'tree '+'a'.encode()*40+b'\n continuation\n\nm'])
def test_malformed_native_commit_headers_rejected(raw):
    with pytest.raises(InvalidTransition):relation.commit(raw)


def test_nested_source_relation_preserves_absent_and_explicit_null():
    original=dict(bundle_sha256='a'*64,ci_source_sha='b'*40,ci_workflow_sha='b'*40,source_ref='refs/pull/1/merge',trigger='pull_request')
    for value in (original,{**original,'source_relation':None}):
        assert ReaCiAttestationEvidence.model_validate(value).model_dump(mode='json')==value
    for value in (dict(witness_sha256='a'*64,reviewed_verifier_sha256='b'*64),dict(witness_sha256='a'*64,reviewed_verifier_sha256='b'*64,approved_base_sha=None)):
        # Nested dispatch base is explicitly typed null; it cannot mimic PR approval.
        assert ReaCiSourceRelationEvidence.model_validate(value).approved_base_sha is None


def test_fresh_authentication_includes_relation_and_revalidates_custody(attested):
    raw,args,_,_=witness()
    root=attested['attestation_root'];root.chmod(0o755)
    path=root/'witness.json';path.write_bytes(raw);path.chmod(0o444);root.chmod(0o555)
    source_pins=ReaCiSourceRelationEvidence(witness_sha256=ci.sha(raw),reviewed_verifier_sha256=args['pins'].reviewed_verifier_sha256,approved_base_sha=args['pins'].approved_base_sha)
    old=attested['compilation_trust']
    deployment=replace(old.ci_attestation,ci_source_sha=args['ci_source_sha'],ci_workflow_sha=args['ci_workflow_sha'],source_relation=replace(args['pins'],witness_root=root))
    trust=replace(old,candidate_sha=args['candidate_sha'],workflow_sha256=args['workflow_sha256'],helper_sha256=args['helper_sha256'],ci_attestation=deployment)
    approved=ReaCiAttestationEvidence(**{k:getattr(deployment,k) for k in ('bundle_sha256','ci_source_sha','ci_workflow_sha','source_ref','trigger')},source_relation=source_pins)
    expected=ci.expected_identity(candidate=trust.candidate_sha,run_id=trust.run_id,run_attempt=trust.run_attempt,source_sha=deployment.ci_source_sha,workflow_sha=deployment.ci_workflow_sha,source_ref=deployment.source_ref,trigger=deployment.trigger)
    attested['install_cli'](raw_result(attested['report_path'].read_bytes(),expected))
    summary,revalidate=ci.authenticate(trust,approved)
    assert summary['candidate_to_ci_source_relation_verified'] is True
    assert summary['independent_compiler_causality_verified'] is False
    assert summary['owning_github_execution_authenticated'] is False
    revalidate()
    path.chmod(0o644);path.write_bytes(raw+b' ');path.chmod(0o444)
    with pytest.raises(InvalidTransition):revalidate()


def test_exporter_ignores_actual_replace_refs_and_shadowed_config(tmp_path, monkeypatch):
    import importlib.util
    raw,args,objects,_=witness()
    repo=tmp_path/'repo';repo.mkdir()
    def git(*argv, data=None):
        return subprocess.run(['/usr/bin/git','-C',str(repo),*argv],input=data,check=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE).stdout
    git('init')
    for oid,item in objects.items():
        assert git('hash-object','-w','-t',item['type'],'--stdin',data=base64.b64decode(item['data_base64'])).strip().decode()==oid
    source=args['ci_source_sha']
    original=base64.b64decode(objects[source]['data_base64'])
    replacement=git('hash-object','-w','-t','commit','--stdin',data=original.replace(b'message',b'hostile')).strip().decode()
    git('replace',source,replacement)
    assert git('cat-file','commit',source)!=original  # Attack exists, not merely environment simulation.
    config=tmp_path/'global-config';config.write_text('[core]\n repositoryformatversion = 999\n[alias]\n cat-file = !exit 1\n')
    monkeypatch.setenv('GIT_CONFIG_GLOBAL',str(config))
    monkeypatch.setenv('GIT_CONFIG_COUNT','1');monkeypatch.setenv('GIT_CONFIG_KEY_0','core.repositoryformatversion');monkeypatch.setenv('GIT_CONFIG_VALUE_0','999')
    monkeypatch.setenv('GIT_REPLACE_REF_BASE','refs/hostile/')
    spec=importlib.util.spec_from_file_location('rea_ci_attestation',Path(__file__).resolve().parents[3]/'scripts/rea_ci_attestation.py')
    import sys
    monkeypatch.syspath_prepend(str(Path(__file__).resolve().parents[3]/'scripts'))
    module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)
    exported=module.export_source_witness(repo,repo,args['candidate_sha'],source)
    assert json.loads(exported)==json.loads(raw)
    relation.verify(exported,**{**args,'pins':replace(args['pins'],witness_sha256=ci.sha(exported))})


@pytest.mark.parametrize('mutation',['writable','hardlink','symlink','bytes','missing','null-approval'])
def test_nested_relation_fails_closed_before_package_audit(db_session,board,attested,tmp_path,mutation):
    from app.services import organization_rea_build as build
    from app.schemas_organization_rea_admission import ReaCompilationEvidence
    from app.services.organization_command import canonical_fingerprint
    from tests.test_organization_rea_build import assert_no_audit
    from tests.test_organization_rea_compilation import correlated_inspect
    raw,args,_,_=witness()
    root=attested['attestation_root'];root.chmod(0o755)
    path=root/'witness.json';path.write_bytes(raw);path.chmod(0o444)
    if mutation=='writable':path.chmod(0o644)
    elif mutation=='hardlink':os.link(path,tmp_path/'other')
    elif mutation=='symlink':path.unlink();path.symlink_to(attested['report_path'])
    elif mutation=='bytes':path.chmod(0o644);path.write_bytes(b'{}');path.chmod(0o444)
    root.chmod(0o555)
    request=attested['request'].model_copy(deep=True)
    request.decision_key='source-'+uuid4().hex;request.supersedes_decision_id=attested['row'].id
    pins=ReaCiSourceRelationEvidence(witness_sha256=ci.sha(raw),reviewed_verifier_sha256=args['pins'].reviewed_verifier_sha256,approved_base_sha=args['pins'].approved_base_sha)
    payload=request.scope.compilation_evidence.model_dump(mode='json');payload['ci_attestation']['source_relation']=pins.model_dump(mode='json') if mutation!='null-approval' else None
    request.scope.compilation_evidence=ReaCompilationEvidence.model_validate(payload)
    row=approve(db_session,board,build.admission.propose_rea_provider_review(db_session,board,request))
    contract=build.admission.resolve_rea_provider_review(db_session,board,decision_id=row.id,trust=attested['trust'])[1]
    old=attested['compilation_trust']
    nested=None if mutation=='missing' else replace(args['pins'],witness_root=root)
    attested.update(row=row,request=request,compilation_trust=replace(old,provider_decision_id=str(row.id),provider_contract_sha256=canonical_fingerprint(contract),ci_attestation=replace(old.ci_attestation,source_relation=nested)))
    with pytest.raises(InvalidTransition):correlated_inspect(db_session,board,attested)
    assert_no_audit(db_session)


@pytest.fixture
def related(attested,db_session,board):
    from app.services import organization_rea_build as build
    from app.schemas_organization_rea_admission import ReaCompilationEvidence
    from app.services.organization_command import canonical_fingerprint
    from tests.test_organization_rea_compilation import rewrite
    raw,args,_,_=witness()
    root=attested['attestation_root'];root.chmod(0o755)
    path=root/'witness.json';path.write_bytes(raw);path.chmod(0o444);root.chmod(0o555)
    pins=ReaCiSourceRelationEvidence(witness_sha256=ci.sha(raw),reviewed_verifier_sha256=args['pins'].reviewed_verifier_sha256,approved_base_sha=args['pins'].approved_base_sha)
    report=attested['report']
    report['repeatability']['context']['candidate']=args['candidate_sha']
    report['repeatability']['recipe'].update(workflow_sha256=args['workflow_sha256'],helper_sha256=args['helper_sha256'])
    rewrite(attested,report)
    request=attested['request'].model_copy(deep=True)
    request.decision_key='related-'+uuid4().hex;request.supersedes_decision_id=attested['row'].id
    payload=request.scope.compilation_evidence.model_dump(mode='json')
    payload.update(candidate_sha=args['candidate_sha'],report_sha256=attested['compilation_trust'].report_sha256,workflow_sha256=args['workflow_sha256'],helper_sha256=args['helper_sha256'])
    payload['ci_attestation'].update(ci_source_sha=args['ci_source_sha'],ci_workflow_sha=args['ci_workflow_sha'],source_relation=pins.model_dump(mode='json'))
    request.scope.compilation_evidence=ReaCompilationEvidence.model_validate(payload)
    row=approve(db_session,board,build.admission.propose_rea_provider_review(db_session,board,request))
    contract=build.admission.resolve_rea_provider_review(db_session,board,decision_id=row.id,trust=attested['trust'])[1]
    old=attested['compilation_trust']
    deployment=replace(old.ci_attestation,ci_source_sha=args['ci_source_sha'],ci_workflow_sha=args['ci_workflow_sha'],source_relation=replace(args['pins'],witness_root=root))
    attested.update(row=row,request=request,witness_path=path,compilation_trust=replace(old,candidate_sha=args['candidate_sha'],workflow_sha256=args['workflow_sha256'],helper_sha256=args['helper_sha256'],provider_decision_id=str(row.id),provider_contract_sha256=canonical_fingerprint(contract),ci_attestation=deployment))
    expected=ci.expected_identity(candidate=args['candidate_sha'],run_id=old.run_id,run_attempt=old.run_attempt,source_sha=args['ci_source_sha'],workflow_sha=args['ci_workflow_sha'],source_ref=deployment.source_ref,trigger=deployment.trigger)
    attested['install_cli'](raw_result(attested['report_path'].read_bytes(),expected))
    return attested


def test_governed_package_inspection_records_only_narrow_relation(db_session,board,related):
    from tests.test_organization_rea_compilation import correlated_inspect
    from app.services import organization_rea_build as build
    from app.models.domain import AuditLog
    from sqlmodel import select
    result=correlated_inspect(db_session,board,related)
    assert result['candidate_to_ci_source_relation_verified'] is True
    assert result['committed_recipe_bytes_match_review'] is True
    for key in ('independent_compiler_causality_verified','source_to_build_verified','publisher_verified','runtime_closure_verified','provider_ready','execution_authorized','live_transport_owned','isolation_verified'):
        assert result[key] is False
    proof=json.loads(db_session.exec(select(AuditLog).where(AuditLog.action==build.ACTION)).one().after_state_json)['ci_attestation']
    assert proof['owning_github_execution_authenticated'] is False
    assert 'objects' not in proof['source_relation'] and str(related['witness_path']) not in json.dumps(proof)


def test_witness_changed_after_audit_rolls_back(db_session,board,related,monkeypatch):
    from tests.test_organization_rea_compilation import correlated_inspect
    from tests.test_organization_rea_build import assert_no_audit
    from app.services import organization_rea_build as build
    original=build.record_audit
    def mutate(*args,**kwargs):
        result=original(*args,**kwargs)
        path=related['witness_path'];path.chmod(0o644);path.write_bytes(path.read_bytes()+b' ');path.chmod(0o444)
        return result
    monkeypatch.setattr(build,'record_audit',mutate)
    with pytest.raises(InvalidTransition):correlated_inspect(db_session,board,related)
    assert_no_audit(db_session)


@pytest.mark.parametrize('mutation',['reversed-parents','one-parent','extra-parent','different-tree'])
def test_rehashed_source_commit_cannot_change_approved_topology(mutation):
    raw,args,objects,encode=witness()
    old=args['ci_source_sha'];item=objects.pop(old)
    data=base64.b64decode(item['data_base64'])
    candidate=args['candidate_sha']
    original=('parent '+'c'*40+'\nparent '+candidate+'\n').encode()
    if mutation=='reversed-parents':changed=('parent '+candidate+'\nparent '+'c'*40+'\n').encode()
    elif mutation=='one-parent':changed=('parent '+candidate+'\n').encode()
    elif mutation=='extra-parent':changed=original+('parent '+'d'*40+'\n').encode()
    else:
        changed=original
        data=b'tree '+b'e'*40+data[45:]
    data=data.replace(original,changed)
    new=relation.object_sha('commit',data)
    objects[new]={'type':'commit','data_base64':base64.b64encode(data).decode()}
    args.update(ci_source_sha=new,ci_workflow_sha=new)
    raw=encode();args['pins']=replace(args['pins'],witness_sha256=ci.sha(raw))
    with pytest.raises(InvalidTransition):relation.verify(raw,**args)
