services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    restart: unless-stopped
    ports:
      - "8008:8000"
      - "9000:9000"
    volumes:
      - woodpecker_server_data:/var/lib/woodpecker/
    environment:
      WOODPECKER_OPEN: "false"
      WOODPECKER_ADMIN: ${WOODPECKER_ADMIN}
      WOODPECKER_HOST: ${WOODPECKER_HOST}
      WOODPECKER_GITHUB: "true"
      WOODPECKER_GITHUB_CLIENT: ${WOODPECKER_GITHUB_CLIENT}
      WOODPECKER_GITHUB_SECRET: ${WOODPECKER_GITHUB_SECRET}
      WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET}
      WOODPECKER_FORCE_IGNORE_SERVICE_FAILURE: "false"

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    command: agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - woodpecker_agent_config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WOODPECKER_SERVER: woodpecker-server:9000
      WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET}
      WOODPECKER_MAX_WORKFLOWS: ${WOODPECKER_MAX_WORKFLOWS:-2}

volumes:
  woodpecker_server_data:
  woodpecker_agent_config:
