import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const read = (relativePath) => readFile(new URL(`../${relativePath}`, import.meta.url), "utf8");

test("Austria Live Organization Cockpit surface is persisted, bounded, and explicit about proof gaps", async () => {
  const [page, api, navigation, sceneComponent, replayComponent, sceneRenderer, lensModel, analytics, cockpitLayout] = await Promise.all([
    read("app/cockpit/live-organization/page.tsx"),
    read("lib/live-organization.ts"),
    read("lib/workspace-navigation.ts"),
    read("components/LivingOrganizationScene.tsx"),
    read("components/LivingOrganizationReplayTimeline.tsx"),
    read("lib/living-organization-scene-renderer.ts"),
    read("lib/living-organization-lenses.ts"),
    read("lib/living-organization-analytics.ts"),
    read("app/cockpit/layout.tsx"),
  ]);

  assert.match(navigation, /label: "Live Organization", href: "\/cockpit\/live-organization"/);
  assert.match(navigation, /pathname\.startsWith\("\/cockpit"\)/);

  assert.match(page, /getLatestAustriaLiveOrganization/);
  assert.match(page, /synthesizeAustriaOwner/);
  assert.match(page, /snapshot\.ready_for_owner_synthesis/);
  assert.match(page, /snapshot\.external_action_authorized/);
  assert.match(page, /snapshot\.provider_model_authority/);
  assert.match(page, /snapshot\.domain_evidence_refs/);
  assert.match(page, /snapshot\.verified_rule_refs/);
  assert.match(page, /snapshot\.source_snapshot_refs/);
  assert.match(page, /specialist\.runtime_quality/);
  assert.match(page, /snapshot\.activities\.map/);
  assert.match(page, /Durable activity lineage/);
  assert.match(page, /Persisted organizational activity/);
  assert.match(page, /activity\.causation_activity_id/);
  assert.match(page, /Provider transcripts, tool logs, and donor event streams are not promoted to organizational truth/);
  assert.match(page, /Runtime economics & quality/);
  assert.match(page, /Persisted specialist runtime signals/);
  assert.match(page, /quality\.total_tokens/);
  assert.match(page, /quality\.estimated_cost_usd/);
  assert.match(page, /quality\.fresh_retrieval_provenance_present/);
  assert.match(page, /quality\.fallback_to_template/);
  assert.match(page, /Missing costs are not inferred as zero|missing costs are not inferred as zero/i);
  assert.match(page, /Telemetry is presentation evidence only/);
  assert.match(page, /does not create OrganizationActivity/);
  assert.match(page, /grant provider\/model authority/);
  assert.match(page, /authorize external action/);
  assert.match(page, /The Cockpit does not simulate a live organization cycle/);
  assert.match(page, /no Evidence is fabricated by the UI/);
  assert.match(page, /regulatory truth is not implied/);
  assert.match(page, /Board authentication required/);
  assert.match(page, /Board access not permitted/);
  assert.match(page, /Live organization unavailable/);
  assert.match(page, /does not infer whether a live cycle exists/);
  assert.match(page, /!loading && !error && !snapshot/);
  assert.doesNotMatch(page, /Math\.random|setInterval\(/);
  assert.doesNotMatch(page, /provider transcript.*OrganizationActivity/i);

  assert.match(api, /export type AustriaLiveRuntimeQuality/);
  assert.match(api, /runtime_quality: AustriaLiveRuntimeQuality \| null/);
  assert.match(api, /estimated_cost_usd: number \| null/);
  assert.match(api, /fresh_retrieval_provenance_present: boolean/);
  assert.match(api, /causation_activity_id: string \| null/);
  assert.match(api, /class LiveOrganizationRequestError extends Error/);
  assert.match(api, /this\.status = status/);
  assert.match(api, /throw new LiveOrganizationRequestError\(response\.status, detail\)/);
  assert.match(api, /createApiFetch\(CLIENT_API_CONFIG\)/);
  assert.match(api, /\/api\/v1\/organization\/transparency\/live-organization\/austria\/latest/);
  assert.match(api, /\/api\/v1\/organization\/live-organization\/austria\/\$\{encodeURIComponent\(rootWorkItemId\)\}\/owner-synthesis/);

  assert.match(page, /getLatestAustriaLivingScene/);
  assert.match(page, /LivingOrganizationSceneView/);
  assert.match(page, /scene\.root_work_item_id !== snapshot\.root_work_item_id/);
  assert.match(page, /does not render mixed canonical states/);
  assert.match(page, /does not synthesize one locally/);
  assert.match(api, /export type LivingSceneCoverage/);
  assert.match(api, /departments: LivingSceneDepartment\[\]/);
  assert.match(api, /missions: LivingSceneMission\[\]/);
  assert.match(api, /conversations: LivingSceneConversation\[\]/);
  assert.match(api, /handoffs: LivingSceneHandoff\[\]/);
  assert.match(api, /incidents: LivingSceneIncident\[\]/);
  assert.match(api, /human_actions: LivingSceneHumanActionRequest\[\]/);
  assert.match(api, /risk_escalations: LivingSceneRiskEscalation\[\]/);
  assert.match(api, /metric_value: number \| null/);
  assert.match(api, /smart_objects: LivingSceneSmartObject\[\]/);
  assert.match(api, /elapsed_seconds: number \| null/);
  assert.match(api, /overdue: boolean/);
  assert.match(api, /open_elapsed_seconds: number/);
  assert.match(api, /specialist_evidence_valid: boolean \| null/);
  assert.match(api, /specialist_evidence_reason: string \| null/);
  assert.match(api, /superseded_by_created_at: string \| null/);
  assert.match(api, /superseded_in_projection_week: boolean/);
  assert.match(api, /export type LivingOrganizationScene/);
  assert.match(api, /\/api\/v1\/organization\/transparency\/live-organization\/scene\/austria\/latest/);
  assert.match(api, /export type OrganizationReplayCoverage/);
  assert.match(api, /export type OrganizationReplayEvent/);
  assert.match(api, /export type OrganizationReplay/);
  assert.match(api, /getLatestAustriaOrganizationReplay/);
  assert.match(api, /\/api\/v1\/organization\/transparency\/live-organization\/replay\/austria\/latest/);
  assert.match(api, /export type OrganizationReplayState/);
  assert.match(api, /getLatestAustriaOrganizationReplayState/);
  assert.match(api, /replay\/austria\/latest\/state/);
  assert.match(page, /LivingOrganizationReplayTimeline/);
  assert.match(page, /replay\.root_work_item_id !== snapshot\.root_work_item_id/);
  assert.match(page, /does not reconstruct history locally/);
  assert.match(replayComponent, /M\.8\.2 · As-of Temporal State Reconstruction/);
  assert.match(replayComponent, /OrganizationActivity is the replay source/);
  assert.match(replayComponent, /Reconstruction uses semantic transition payloads only/);
  assert.match(replayComponent, /data-replay-coverage-state/);
  assert.match(replayComponent, /pre_epoch_partial/);
  assert.match(replayComponent, /partial_no_epoch/);
  assert.match(replayComponent, /Transcript content is not persisted and is never reconstructed/);
  assert.match(replayComponent, /Inspect state here/);
  assert.match(replayComponent, /getLatestAustriaOrganizationReplayState/);
  assert.match(replayComponent, /data-replay-state-authoritative/);
  assert.match(replayComponent, /Current domain rows are not/);
  assert.match(replayComponent, /unsupported_dimensions\.join/);
  assert.match(replayComponent, /RiskEscalation records and SourceSnapshot references are not/);
  assert.doesNotMatch(replayComponent, /fetch\(|XMLHttpRequest|Math\.random|setInterval/);
  assert.match(sceneComponent, /M\.7\.4 · GPU FLOW field TRIAL · Iteration 1/);
  assert.match(sceneComponent, /data-active-lens=\{activeLens\}/);
  assert.match(sceneComponent, /buildStructuredFlowBaseline/);
  assert.match(sceneComponent, /OWNER_ANALYTICAL_QUERIES/);
  assert.match(sceneComponent, /data-flow-authoritative="false"/);
  assert.match(sceneComponent, /Directed work routing & bottleneck signals/);
  assert.match(sceneComponent, /Control surface · GPU field TRIAL remains not promoted/);
  assert.match(sceneComponent, /data-owner-query-result/);
  assert.match(sceneComponent, /GPU FLOW field TRIAL/);
  assert.match(sceneComponent, /Control surface · GPU field TRIAL remains not promoted/);
  assert.match(sceneComponent, /data-conversation-id=\{conversation\.conversation_id\}/);
  assert.match(sceneComponent, /data-handoff-activity-id=\{handoff\.activity_id\}/);
  assert.match(sceneComponent, /Owner command mode · view-only foundation/);
  assert.match(sceneComponent, /No POST · no canonical mutation/);
  assert.match(sceneComponent, /OWNER_LENS_VIEW_COMMANDS/);
  assert.match(sceneComponent, /aria-pressed=\{activeLens === lens\.key\}/);
  assert.match(sceneComponent, /lens-deemphasized/);
  assert.match(lensModel, /LIVING_ORGANIZATION_LENS_KEYS/);
  assert.match(lensModel, /"organization"/);
  assert.match(lensModel, /"flow"/);
  assert.match(lensModel, /Authority levels are not treated as autonomy/);
  assert.match(lensModel, /activity volume is not productivity/);
  assert.match(lensModel, /No canonical organization runtime-cost ledger is available to this scene/);
  assert.match(lensModel, /No canonical Incident model is available to this scene/);
  assert.match(lensModel, /Structured directed WorkItem topology/);
  assert.match(lensModel, /GPU fluid\/field remains a separate trial/);
  assert.match(lensModel, /activeLens === "organization" \|\| tags\.includes\(activeLens\)/);
  assert.doesNotMatch(lensModel, /fetch\(|XMLHttpRequest|synthesizeAustriaOwner/);
    assert.match(sceneComponent, /data-scene-plane="deterministic"/);
  assert.match(sceneComponent, /scene\.deterministic\.departments/);
  assert.match(sceneComponent, /scene\.deterministic\.missions/);
  assert.match(sceneComponent, /scene\.deterministic\.conversations/);
  assert.match(sceneComponent, /scene\.deterministic\.handoffs/);
  assert.match(sceneComponent, /CANONICAL CONVERSATIONS/);
  assert.match(sceneComponent, /CANONICAL HANDOFFS/);
  assert.match(sceneComponent, /conversation\.opened_activity_id/);
  assert.match(sceneComponent, /conversation\.latest_activity_id/);
  assert.match(sceneComponent, /conversation\.authority_effect/);
  assert.match(sceneComponent, /conversation\.transcript_persisted/);
  assert.match(sceneComponent, /handoff\.causation_activity_id/);
  assert.match(sceneComponent, /conversation\.status !== "open"/);
  assert.match(sceneComponent, /scene\.deterministic\.human_actions/);
  assert.match(sceneComponent, /scene\.deterministic\.risk_escalations/);
  assert.match(sceneComponent, /required_owner_action/);
  assert.match(sceneComponent, /record_fingerprint/);
  assert.match(sceneComponent, /scene\.deterministic\.smart_objects/);
  assert.match(sceneComponent, /data-smart-object-state/);
  assert.match(sceneComponent, /Living Organization Smart Objects/);
  assert.match(sceneComponent, /Canonical department topology/);
  assert.match(sceneComponent, /renderModel\.departmentZones/);
  assert.match(sceneComponent, /data-department-zone/);
  assert.match(sceneComponent, /data-department=\{employee\.department\}/);
  assert.match(sceneComponent, /item\.label/);
  assert.match(sceneComponent, /item\.canonical_basis/);
  assert.doesNotMatch(sceneComponent, /<strong>Mission Board<\/strong>/);
  assert.match(sceneComponent, /Presence/);
  assert.match(sceneComponent, /scene\.predictive\.enabled/);
  assert.match(sceneComponent, /scene\.environmental\.enabled/);
  assert.match(sceneComponent, /scene\.truth\.renderer_authoritative/);
  assert.match(sceneRenderer, /LIVING_SCENE_RENDERER_TARGET = "three-webgpu"/);
  assert.match(sceneRenderer, /departmentZones/);
  assert.match(sceneRenderer, /employee\.department === department\.department_key/);
  assert.match(sceneRenderer, /workItem\.department === department\.department_key/);
  assert.match(sceneRenderer, /smartObjects: scene\.deterministic\.smart_objects/);
  assert.match(sceneRenderer, /sceneAuthoritative: false/);
  assert.match(sceneRenderer, /flowTrial: FlowFieldTrialModel/);
  assert.match(sceneRenderer, /buildFlowFieldTrialModel\(flowBaseline\)/);
  assert.doesNotMatch(sceneRenderer, /Math\.random|setInterval|fetch\(/);
  assert.match(analytics, /buildStructuredFlowBaseline/);
  assert.match(analytics, /blocked_over_20_minutes/);
  assert.match(analytics, /open_elapsed_seconds >= thresholdSeconds/);
  assert.match(analytics, /\["R4", "R5"\]\.includes/);
  assert.match(analytics, /Risk attention alone is not treated as Owner authority/);
  assert.match(analytics, /K\.1 specialist execution evidence only/);
  assert.match(analytics, /superseded_in_projection_week/);
  assert.match(analytics, /successor decision creation/);
  assert.match(analytics, /Specialist runtime estimates remain telemetry/);
  assert.match(analytics, /topology is not promoted to dependency truth/);
  assert.doesNotMatch(analytics, /Date\.now|new Date|Date\.parse|fetch\(|XMLHttpRequest|synthesizeAustriaOwner/);
  assert.match(cockpitLayout, /living-scene\.css/);

});
